config/routes.rb
Rails4sample::Application.routes.draw do
  resources :tasks do
    get "realtime", on: :collection
    get "realtime_show", on: :collection
  end

  root 'tasks#index'

  get 'progress' => 'progress#index'
  get 'progress/index'
  get 'progress/show'
  get 'progress/attack'
  get 'progress/attack_show'
  get 'progress/attack_end'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/progress_controller.rb
require 'reloader/sse'

class ProgressController < ApplicationController
  include ActionController::Live

  #-------#
  # index #
  #-------#
  def index
    # SSE expects the `text/event-stream` content type
    response.headers['Content-Type'] = 'text/event-stream'

    sse = Reloader::SSE.new(response.stream)

    begin
      total = 0

      (0..100).step(10).each{ |i|
        puts "[ #{i} ]"
        sse.write( "#{Time.now.strftime("%Y/%m/%d %H:%M:%S")}" + " - #{i}" )
        total += i
        sleep( rand(1..3) )
      }

      puts "[ total : #{total} ]"

      sse.write( "#{Time.now.strftime("%Y/%m/%d %H:%M:%S")}" + " - #{total}", event: 'refresh' )

      # 接続終了送信
#      sse.write("stream_end")
    rescue IOError
      # When the client disconnects, we'll get an IOError on write
    ensure
      sse.close
    end
  end

  #------#
  # show #
  #------#
  def show
  end

  #--------#
  # attack #
  #--------#
  def attack
    response.headers['Content-Type'] = 'text/event-stream'
    sse = Reloader::SSE.new(response.stream)

    begin
      url  = "https://canbus.herokuapp.com/"
      url  = URI.parse( url )
      http = Net::HTTP.new( url.host, url.port )
      http.use_ssl = true if url.port == 443
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE if url.port == 443
      path = url.path
      path += "?" + url.query unless url.query.nil?

      str = ""

      1.upto(10){ |i|
        response = http.get( path )
        status   = response.inspect.delete("#<>")
        str      = "[ #{i} | #{Time.now.strftime("%Y/%m/%d %H:%M:%S")}" + " | #{url} | #{status} | #{$all_stop} ]"
        puts str
      }

      sse.write( str, event: 'refresh' )

      # 接続終了送信
      if session[:realtime_end] == true or $all_stop.present?
        sse.write( "stream_end", event: 'refresh' )
      end
    rescue IOError
      # When the client disconnects, we'll get an IOError on write
    ensure
      sse.close
    end
  end

  #-------------#
  # attack_show #
  #-------------#
  def attack_show
    session[:realtime_end] = false
  end

  #------------#
  # attack_end #
  #------------#
  def attack_end
    $all_stop = params[:all_stop]
    session[:realtime_end] = true
  end
end

app/controllers/tasks_controller.rb
require 'reloader/sse'

class TasksController < ApplicationController
  include ActionController::Live
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    session[:realtime_end] = true
    @tasks = Task.order( created_at: :desc ).all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  #----------#
  # realtime #
  #----------#
  def realtime
    response.headers['Content-Type'] = 'text/event-stream'
    sse = Reloader::SSE.new(response.stream)

    begin
      tasks = Task.all
      Task.create( title: "タスク#{tasks.length}", content: "コンテント#{tasks.length}" ) if tasks.length <= 9000

      puts "[ #{Time.now.strftime("%Y/%m/%d %H:%M:%S")}" + " - #{tasks.length} ]"
      sse.write( "#{Time.now.strftime("%Y/%m/%d %H:%M:%S")}" + " - #{tasks.length}", event: 'refresh' )

      # 接続終了送信
      if session[:realtime_end] == true
        sse.write("stream_end")
      end
    rescue IOError
      # When the client disconnects, we'll get an IOError on write
    ensure
      sse.close
    end
  end

  #---------------#
  # realtime_show #
  #---------------#
  def realtime_show
    session[:realtime_end] = false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4sample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to( "トップ", root_path ) %>
 | <%= link_to( "タスク", tasks_path ) %>
 | <%= link_to( "リアルタイム", realtime_show_tasks_path ) %>
<br />
<%= link_to( "アタック", progress_attack_show_path ) %>
 | <%= link_to( "アタックエンド", progress_attack_end_path ) %>
 | <%= link_to( "オールストップ", progress_attack_end_path( all_stop: "true" ) ) %>

<br />

<%= yield %>

</body>
</html>

app/views/progress/attack.html.erb
<%= @result.tapp %>

app/views/progress/attack_end.html.erb
<p>all_stop : <%= $all_stop %><p>
<p>realtime_end : <%= session[:realtime_end] %><p>

app/views/progress/attack_show.html.erb
<h1>Attack Show</h1>

<div id="refresh"></div>

<hr />

<script type="text/javascript">
  jQuery(document).ready(function() {
    setTimeout(function() {
      var source = new EventSource('/progress/attack');
      source.addEventListener('refresh', function(e) {
        $("#refresh").prepend(event.data + "<br>");

        // 接続終了判定
        if (event.data == 'stream_end') { source.close() };
      });
    }, 1);
  });
</script>

app/views/progress/show.html.erb
<h1>progress#show</h1>

<h3>Total</h3>

<div id="refresh"></div>

<hr />

<h3>Progress</h3>

<div id="progress"></div>

<script type="text/javascript">
  jQuery(document).ready(function() {
    setTimeout(function() {
      // 接続開始
      var source = new EventSource('/progress/index');

      // サーバー側イベントの共通ハンドラを定義
      function eventLogger(event){
        $("#progress").prepend(event.data + "<br>");

        // 接続終了判定
        if (event.data == 'stream_end') { source.close() };
      }

      // messageイベントのハンドラを設定
      source.onmessage = eventLogger;
    }, 10);
  });
</script>

<script type="text/javascript">
  jQuery(document).ready(function() {
    setTimeout(function() {
      var source = new EventSource('/progress/index');
      source.addEventListener('refresh', function(e) {
        $("#refresh").prepend(event.data + "<br>");
        // window.location.reload();

        // 接続終了判定
        if (event.data == 'stream_end') { source.close() };
      });
    }, 20);
  });
</script>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Deadline</th>
      <th>Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.deadline %></td>
      <td><%= task.count %></td>
      <td><%= link_to 'Show', task %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/realtime_show.html.erb
<h1>RealTime Show</h1>

<div id="tasks_count"></div>

<hr />

<script type="text/javascript">
  jQuery(document).ready(function() {
    setTimeout(function() {
      var source = new EventSource('/tasks/realtime');
      source.addEventListener('refresh', function(e) {
        $("#tasks_count").prepend(event.data + "<br>");

        // 接続終了判定
        if (event.data == 'stream_end') { source.close() };
      });
    }, 1);
  });
</script>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Count:</strong>
  <%= @task.count %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>